


# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)

shinyUI(fluidPage(
   tags$head(includeScript("google-analytics.js")),
   
   titlePanel("Tidy Up PBR Data"),
   sidebarLayout(
      sidebarPanel(
         fluidRow(
            column(7, fileInput(
               'file1',
               'Choose data file to upload',
               accept = c(
                  'application/x-zip-compressed',
                  'text/csv',
                  'text/comma-separated-values',
                  'text/tab-separated-values',
                  'text/plain',
                  '.csv',
                  '.tsv'
               )
            )),
            column(
               5,
               numericInput('interval', 'Averaging interval [min]', 1, 0.5, 10, 0.1, '200px'),
               downloadButton('downloadData', 'Download')
            )
         ),
         tags$hr(),
         fluidRow(
            column(4, checkboxInput('header', 'Header', TRUE)),
            column(4, radioButtons(
               'sep', 'Separator',
               c(
                  Comma = ',',
                  Semicolon = ';',
                  Tab = '\t'
               ),
               ','
            )),
            column(4, radioButtons(
               'dec', 'Decimal mark',
               c('Point' = '.',
                 'Comma' = ','),
               '.'
            ))
         ),
         tags$hr(),
         p(
            "@author CzechGlobe - Department of Adaptive Biotechnologies (JaCe)"
         ),
         fluidRow(column(
            12,
            actionLink("register", label = "Register to support development of additional PBR tools"),
            conditionalPanel(
               "input.register",
               textInput("name", label = "First name", value = "First name"),
               textInput("surname", label = "Last name", value = "Last name"),
               textInput("email", label = "Email", value = "@"),
               textInput("organization", label = "Organization", value = "Organization"),
               textInput("department", label = "Department", value = "Department"),
               actionButton("send", label = "Send"),
               p("@email cerveny.j@czechglobe.cz")
            )
         ))
         ,
         width = 5
      ),
      mainPanel(
         actionLink("help", label = "Help"),
         conditionalPanel(
            "input.help",
            p(
               "This tool was developed to simplify manipulation with untidy data generated by Photon Systems Instruments (PSI) photobioreactor sofware. The data uploaded to this tool are expected in CSV (or TSV) multi-column format, containig each column description in the first row. Most simple untidy data preparation procedure is to export data from the software in ODS format and then export last Data sheet as CSV file in Excel."
            ),
            p(
               "In general this tool can be used on any numeric data table, e.g. for large datasets averaging, etc."
            )
         ),
         strong(textOutput("count")),
         br(),
         strong(textOutput("filename")),
         em(textOutput("filesize")),
         br(),
         textOutput("inputdim"),
         textOutput("processeddim")
         ,
         width = 5
      )
   )
))