# This is the user-interface definition of a Shiny web application.
# You can find out more about building applications with Shiny here:
#
# http://shiny.rstudio.com
#

library(shiny)

shinyUI(fluidPage(
   tags$head(includeScript("google-analytics.js")),
   titlePanel("Tidy Up PBR Data", windowTitle = "Tidy Up Data"),
   sidebarLayout(
      sidebarPanel(
         fluidRow(
            column(7, fileInput(
               'datafile',
               'Choose data file to upload',
               accept = c(
                  'application/x-zip-compressed',
                  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                  'text/csv',
                  'text/comma-separated-values',
                  'text/tab-separated-values',
                  'text/plain',
                  '.xlsx',
                  '.csv',
                  '.tsv'
               )
            )),
            column(
               5,
               numericInput('interval', 'Averaging interval [min]', 1, 0.5, 10, 0.1, '200px'),
               downloadButton('downloadData', 'Download')
            )
         ),
         tags$hr(),
         tags$p(
            "For plan text data formats:"
         ),
         fluidRow(
            column(4, checkboxInput('header', 'Header', TRUE)),
            column(4, radioButtons(
               'sep', 'Separator',
               c(
                  Comma = ',',
                  Semicolon = ';',
                  Tab = '\t'
               ),
               ','
            )),
            column(4, radioButtons(
               'dec', 'Decimal mark',
               c('Point' = '.',
                 'Comma' = ','),
               '.'
            ))
         ),
         tags$hr(),
         p(
            "@author CzechGlobe - Department of Adaptive Biotechnologies (JaCe)"
         ),
         fluidRow(column(
            12,
            actionLink("register", label = "Register to support development of additional PBR tools"),
            conditionalPanel(
               "input.register",
               textInput("name", label = "First name", value = "First name"),
               textInput("surname", label = "Last name", value = "Last name"),
               textInput("email", label = "Email", value = "@"),
               textInput("organization", label = "Organization", value = "Organization"),
               textInput("department", label = "Department", value = "Department"),
               actionButton("send", label = "Send"),
               p(
                  "@email cerveny.j@czechglobe.cz"
               )
            )
         ))
         ,
         width = 5
      ),
      mainPanel(
         strong(textOutput("count")),
         br(),
         strong(textOutput("filename")),
         em(textOutput("filesize")),
         br(),
         textOutput("inputdim"),
         textOutput("processeddim"),
         width = 7
      )
   ),
   fluidRow(
      column(
         3,
         tags$img(src = "img/Logo-CzechGlobe.jpg", alt = "CzechGlobe", height = 60, align = "top")
      ),
      column(
         2,
         tags$img(src = "img/Logo-C4Sys.jpg", alt = "C4Sys", height = 40, align = "right")
      ),
      column(
         1,
         br()
      ),
      column(
         5,
         actionLink("help", label = "Help"),
         conditionalPanel(
            "input.help",
            p(
               "This tool was developed to simplify manipulation with untidy data generated by Photon Systems Instruments (PSI) photobioreactor sofware. The data uploaded to this tool are expected in Excel (.xlsx) or plain text tabular data CSV (or TSV) format."
            ),
            p(
               "For PSI photobioreactor software expoerted data, the most simple untidy data preparation procedure is to export data from the software in ODS format and then either save the file as .xlsx Excel format or export the last sheet (Data) as CSV file."
            ),
            p(
               "In general this tool can be used on any numeric data table, e.g. for large datasets tidying up, averaging, etc."
            )
         )
      )
   )
))